### ISSUE TITLE
great work

### ISSUE THREAD

**Issue by leha-code** [ravenspired/mcpi-cheats#1]
I am doing somethnglike this! Howabout joining forces?

**Comment by ravenspired** [comment]
This project kind of died a while back when I had other stuff to do and forgot about it.
That being said, I would love to collaborate and have this take off.

**Comment by ravenspired** [comment]
On a side note, I am curios how you found this project. Google?

**Comment by leha-code** [comment]
nah
i was searching for minecraft pi projecrs on git hub and found you. I starred a lot of then so i can get back to them. also you can just set the position to -62 or something there. instead of all this -47325723857903278493708905 you did in kill. and mcpi zero is just a wrapper not the commans/chat engine. privet anton! ya toje russki!
